after_success:
  - pip install coveralls
  - coveralls

stages:
  - test

matrix:
  include:
    - stage: test
      name: "Ubuntu Bionic python 3.6"
      language: python
      os: linux
      dist: bionic
      python: 3.6
      script: travis_wait 40 bash travis/install_test_linux.sh
    - stage: test
      name: "Ubuntu Bionic python 3.7"
      language: python
      os: linux
      dist: bionic
      python: 3.7
      script: travis_wait 40 bash travis/install_test_linux.sh
  allow_failures:
    - stage: test
      name: "Windows Python 3.6"
      language: shell
      env: TRAVIS_PYTHON_VERSION=3.6
      os: windows
      before_install:
        - source travis/install_windows.sh
      script: travis_wait 40 bash travis/test_windows.sh
    - stage: test
      name: "Windows Python 3.7"
      language: shell
      env: TRAVIS_PYTHON_VERSION=3.7
      os: windows
      before_install:
        - source travis/install_windows.sh
      script: travis_wait 40 bash travis/test_windows.sh
#    - stage: test
#      name: "macOS Python 3.6"
#      os: osx
#      language: shell
#      env: TRAVIS_PYTHON_VERSION=3.6
#      script: travis_wait 40 bash travis/install_test_osx.sh
    - stage: test
      name: "macOS Python 3.7"
      os: osx
      language: shell
      env: TRAVIS_PYTHON_VERSION=3.7
      script: travis_wait 40 bash travis/install_test_osx.sh
notifications:
  email:
    recipients:
    - adam.tyson@ucl.ac.uk
    on_success: change
    on_failure: always
deploy:
  - provider: pypi
    user: __token__
    password:
      secure: fJBkqyWlaeg7sYIm+V65RZneAfOULwoubmfmbJrRVJnXA04VHarfpTMPx0G/li8cuTtejMTd9KJcShF1kU8IsB0BkeBDuckzdcMUVl/gd75zJQmdrOiRUDf+F4IXIY5wGDMUcmI3G2/YTDkLp7FOvRxSzQU/0woHauWk1Rl7azk7CxI7zOC1GgLpZXIeZf5cvPMneZ63EboT6rQxJ2UHkUlVxnr1uZYSXC1ICK7YwPf72p61BdxnL2e0qmjDpo2/k8rxdRDR6k7dDhSDkwCBAMaPclX0mgqsOuce+tD4gsA1jz3etrD8v+GS8ZxTgf19SNgvYDmVFwr8RAjg5wTbj1zJuv2a99Own/BgiIGEb8k2lhZypDWw+sJbfY2mzz9gB16e3ceudZLAGuOO1oFkj5fnmPYvLD3bZ8YubWpbLPl3Q24YmvJBb+ILRNqpYq8ipH4/uAuZ0yr3fdvkjuXdJY6r29QsNx7CTNIJUvg1JZluty8RB+PK6AbSUDDJYrJmxkiJzKhj9xnz5+HEsc1JEVHakvaQax+xDW6qPNPd/Qroy1505z0DRMuh3AWPxp8YrCmawDMiAgkmTjY+GjW3eRFgotjAa8M4ofzez1crb2MYyFB41JQ9V99G2ccNXT5ObZ9+6amsz4VecV7Vle/RMWqGCojiUhZa64XfSLK2Oj8=
    distributions: sdist bdist_wheel
    skip_existing: true
    on:
      branch: master
      tags: true
